controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
login:
    path: /login
    controller: App\Controller\SecurityController::login

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    
reset_password_request:
    path: /reset-password
    controller: App\Controller\ResetPasswordController::request

reset_password:
    path: /reset-password/reset
    controller: App\Controller\ResetPasswordController::reset
